### ISSUE TITLE
Make script not check for installation of requirements each run

### ISSUE THREAD

**Issue by jarodburchill** [jarodburchill/ProjectAutomation#35]
Maybe make the user install the requirements.txt themselves... unless there are any other ideas?

**Comment by MisterWhopper** [comment]
In the fix for issue #11 I partly address this; I will be implementing a change where the script, on first run, will write the user's username to the script.config file, so that way all they have to type in is either their password or PIN. When I get that PR in, we can change the script to check if that variable is already set; if it is, then we won't check requirements. If not, then we can check requirements

**Comment by jarodburchill** [comment]
@MisterWhopper Good to know are you almost ready to send in that PR?
